server:
  port: 8082
spring:
  profiles:
    active: local
  cloud:
    stream:
      function:
        definition: streamConsumer
      bindings:
        streamConsumer-in-0:
          destination: domains-active
      kafka:
        bindings:
          streamConsumer-in-0:
            consumer:
              configuration:
                value:
                  deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      binder:
        brokers:
          - localhost:9091
          - localhost:9092
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: "*"
allow:
  auto:
    create:
      topics: false